services:
  - type: web
    name: qld-xml-url-extractor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    plan: free